/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASPRAKTIKUM;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author finaa
 */
public class GUI_bukupelajaran extends javax.swing.JFrame  {

    /**
     * Creates new form GUI_bukupelajaran
     */
    public GUI_bukupelajaran() {
        initComponents();
        DefaultTableModel dataBukuPelajaran = (DefaultTableModel)tabel_buku_pelajaran.getModel();
        int rowCount = dataBukuPelajaran.getRowCount();
        while (rowCount > 0 )
        {
            dataBukuPelajaran.removeRow(rowCount - 1);
            rowCount = dataBukuPelajaran.getRowCount();
        }
    }
    
       public void clear() {
 txt_judulbuku.setText("");
 txt_pengarang.setText("");
 txt_penerbit.setText("");
 txt_thnterbit.setText("");
 txt_edisi.setText("");
 txt_mapel.setText(" ");
 //txt_binggris.clearSelection();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_judulbuku = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        txt_thnterbit = new javax.swing.JTextField();
        txt_mapel = new javax.swing.JTextField();
        txt_edisi = new javax.swing.JTextField();
        cmb_pilih = new javax.swing.JComboBox<>();
        txtSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_buku_pelajaran = new javax.swing.JTable();
        txtHapus = new javax.swing.JButton();
        txtBatal = new javax.swing.JButton();
        txtClose = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BUKU PELAJARAN");

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Penerbit");

        jLabel5.setText("Tahun Terbit");

        jLabel6.setText("Mata Pelajaran");

        jLabel7.setText("Edisi");

        jLabel8.setText("Tingkat");

        cmb_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "SMK", "UMUM" }));

        txtSimpan.setText("Simpan");
        txtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpanActionPerformed(evt);
            }
        });

        tabel_buku_pelajaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Judul Buku", "Pengarang", "Penerbit", "Tahun Terbit", "Mata Pelajaran", "Edisi", "Tingkat"
            }
        ));
        jScrollPane2.setViewportView(tabel_buku_pelajaran);

        txtHapus.setText("Hapus");
        txtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHapusActionPerformed(evt);
            }
        });

        txtBatal.setText("Batal");
        txtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalActionPerformed(evt);
            }
        });

        txtClose.setText("Close");
        txtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCloseActionPerformed(evt);
            }
        });

        Search.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_judulbuku)
                            .addComponent(txt_pengarang)
                            .addComponent(txt_penerbit)
                            .addComponent(txt_thnterbit)
                            .addComponent(txt_mapel)
                            .addComponent(txt_edisi)
                            .addComponent(cmb_pilih, 0, 205, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSimpan)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtHapus)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtBatal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtClose))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Search))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_judulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_thnterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_mapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_edisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmb_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSimpan)
                    .addComponent(txtHapus)
                    .addComponent(txtBatal)
                    .addComponent(txtClose))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
        // TODO add your handling code here:
        // Menampilkan pesan dialog bahwa data telah ditambahkan ke tabel 
JOptionPane.showMessageDialog(null, "Data anda Ditambahkan Ke tabel");
 // Mengambil model data dari tabel
 DefaultTableModel dataBukuPelajaran = (DefaultTableModel) tabel_buku_pelajaran.getModel();
 // Inisialisasi sebuah ArrayList bernama 'list'
 List list = new ArrayList<>();
 // Mengatur tabel untuk membuat kolom dari model secara otomatis
tabel_buku_pelajaran.setAutoCreateColumnsFromModel(true);
 // Membuat instance dari kelas Mahasiswa
 Buku_Pelajaran bukuA1 = new Buku_Pelajaran();
 // Mengatur data NIM menggunakan nilai dari komponen txtNim
 bukuA1.dataJudul(txt_judulbuku.getText());
 // Mengatur data Nama menggunakan nilai dari komponen txtNama
 bukuA1.dataPengarang(txt_pengarang.getText());
 // Mengatur jenis kelamin sesuai dengan radio button yang dipilih
 // Mengatur data Prodi menggunakan nilai dari komponen txtProdi
  bukuA1.dataPenerbit(txt_penerbit.getText());
 // Mengatur data Angkatan menggunakan nilai dari komponen txtAngkatan
  bukuA1.datathnTerbit(Integer.parseInt(txt_thnterbit.getText()));
 // Mengatur data Alamat menggunakan nilai dari komponen txtAlamat
 bukuA1.dataMapel(txt_mapel.getText());
 bukuA1.dataEdisi(txt_edisi.getText());
 
 String selectedTingkat = (String) cmb_pilih.getSelectedItem();
    String tingkatText = "";
    
    if (selectedTingkat.equals("SD")) {
        tingkatText = "Sekolah Dasar";
    } else if (selectedTingkat.equals("SMP")) {
        tingkatText = "Sekolah Menengah Pertama";
    } else if (selectedTingkat.equals("SMA")) {
        tingkatText = "Sekolah Menengah Atas";
    } else if (selectedTingkat.equals("SMK")) {
        tingkatText = "Sekolah Menengah Kejuruan";
    } else if (selectedTingkat.equals("UMUM")) {
        tingkatText = "Umum";
    }
 // Menambahkan data-data dari objek Mahasiswa ke dalam ArrayList 'list'
 list.add(bukuA1.cetakJudul());
 list.add(bukuA1.cetakPengarang());
 list.add(bukuA1.cetakPenerbit());
 list.add(bukuA1.cetakThnterbit());
 list.add(bukuA1.cetakMapel());
 list.add(bukuA1.cetakEdisi());
 list.add(tingkatText);
 //list.add(bukuA.cetakAlamat());
 // Menambahkan baris baru ke model tabel menggunakan data dari ArrayList 'list'
 dataBukuPelajaran.addRow(list.toArray());
 // Memanggil fungsi 'clear' untuk membersihkan nilai dari komponen
 clear();
        
   /** boolean isAuthenticated = matematika2A.cekEdisi(edisi);
    if(isAuthenticated)
        {
            JOptionPane.showMessageDialog(rootPane, "Buku " + matematika2A.judulBuku + " Tersedia.");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Maaf, Buku " + matematika2A.judulBuku + " Tidak Tersedia Karena Edisi Khusus.");
        }**/
        
   /** String selectedTingkat = (String) cmb_pilih.getSelectedItem();
    String tingkatText = "";
    
    if (selectedTingkat.equals("SD")) {
        tingkatText = "Sekolah Dasar";
    } else if (selectedTingkat.equals("SMP")) {
        tingkatText = "Sekolah Menengah Pertama";
    } else if (selectedTingkat.equals("SMA")) {
        tingkatText = "Sekolah Menengah Atas";
    } else if (selectedTingkat.equals("SMK")) {
        tingkatText = "Sekolah Menengah Kejuruan";
    } else if (selectedTingkat.equals("UMUM")) {
        tingkatText = "Umum";
    }**/
    }//GEN-LAST:event_txtSimpanActionPerformed

    private void txtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_txtBatalActionPerformed

    private void txtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dataBukuPelajaran = (DefaultTableModel)tabel_buku_pelajaran.getModel();
        int rowCount = dataBukuPelajaran.getRowCount();
        while (rowCount > 0)
        {
            dataBukuPelajaran.removeRow(rowCount - 1);
            rowCount = dataBukuPelajaran.getRowCount();
        }
    }//GEN-LAST:event_txtHapusActionPerformed

    private void txtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_bukupelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_bukupelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_bukupelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_bukupelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_bukupelajaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JComboBox<String> cmb_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_buku_pelajaran;
    private javax.swing.JButton txtBatal;
    private javax.swing.JButton txtClose;
    private javax.swing.JButton txtHapus;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton txtSimpan;
    private javax.swing.JTextField txt_edisi;
    private javax.swing.JTextField txt_judulbuku;
    private javax.swing.JTextField txt_mapel;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_thnterbit;
    // End of variables declaration//GEN-END:variables
}
